name: 'Invoke QCR Release Hooks'
description: 'Invokes the QCR Release Hooks to rebuild release indexes'
author: 'Gavin Suddrey'
branding:
  icon: archive
  color: orange
inputs:
  repo:
    description: 'Repo name'
    required: true
  ref:
    description: 'Repo tag'
    required: true
  files:
    description: 'Release files to upload.'
    required: true
  packages:
    description: 'Stringified YAML describing generated packages for distro'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
